version: '2.1'
services:
  nominatim:
    #image: bringnow/nominatim
    image: lsaggese/tileserver
    volumes:
      - ${IMPORT_DATA_DIR:-./volumes/importdata}:/importdata
    environment:
      - PGHOST=postgis
      - PLANET_DATA_URL=${PLANET_DATA_URL:-http://download.geofabrik.de/europe/monaco-latest.osm.pbf}
      - OSM2PGSQL_CACHE=${OSM2PGSQL_CACHE:-14000}
    ports:
      - ${EXTERNAL_PORT:-0.0.0.0:8080}:80
  postgis:
    image: mdillon/postgis:9.4
    environment:
      - POSTGRES_DB=tileserver
      - POSTGRES_USER=tileserver
      - POSTGRES_PASSWORD=tileserver
    volumes:
      - tileserver-database:/var/lib/postgresql/data
      - ./postgis/set-auth.sh:/docker-entrypoint-initdb.d/set-auth.sh
      - ./postgis/initdb-gis.sh:/docker-entrypoint-initdb.d/postgis.sh
      - ./postgis/tune-postgres.sh:/docker-entrypoint-initdb.d/tune-postgres.sh
    volumes_from:
      - postgis:ro # Needed for the Tileserver PostgreSQL module
volumes:
  tileserver-database:
    external: true
