version: '2.1'
services:
  nominatim:
    #image: bringnow/nominatim
    image: lsaggese/nominatim
    volumes:
      - ${IMPORT_DATA_DIR:-./volumes/importdata}:/importdata
    environment:
      - PGHOST=postgis
      - PLANET_DATA_URL=${PLANET_DATA_URL:-http://download.geofabrik.de/europe/monaco-latest.osm.pbf}
      - OSM2PGSQL_CACHE=${OSM2PGSQL_CACHE:-14000}
    ports:
      - ${EXTERNAL_PORT:-127.0.0.1:8080}:80
  postgis:
    image: mdillon/postgis:9.4
    environment:
      - POSTGRES_DB=nominatim
      - POSTGRES_USER=nominatim
      - POSTGRES_PASSWORD=nominatim
    volumes:
      - nominatim-database:/var/lib/postgresql/data
      - ./postgis/set-auth.sh:/docker-entrypoint-initdb.d/set-auth.sh
      - ./postgis/skip-initdb-postgis.sh:/docker-entrypoint-initdb.d/postgis.sh
      - ./postgis/tune-postgres.sh:/docker-entrypoint-initdb.d/tune-postgres.sh
    volumes_from:
      - nominatim:ro # Needed for the Nominatim PostgreSQL module
volumes:
  nominatim-database:
    external: true
